### PR TITLE
BossFight Prototype

### PR DESCRIPTION
**Pull request by darktoastbrot**
prototype ready for review

### CODE REVIEW

**Comment by ProducerPhil** [comment]
I trust Patrick on this.

**Comment by ProducerPhil** [comment]
Where do I approve this?^^

**Comment by truepaddii** [comment]
@ProducerPhil 
** This didn't work because Git LFS wasn't properly configured on all dev machines. We'll fix that asap.**

**Comment by ProducerPhil** [comment]
@truepaddii Ok, let me know if you need me for anything or if I'm the issue here.^^
And when we can continue working.

**Pull request merged**
